name: "Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan
        run: |
          pwd
          pip3 install wheel setuptools
          pip3 install conan
          export PATH=$PATH:/home/runner/.local/bin
          conan --version

      - name: Setup the Conan profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install dependencies
        run: conan install conanfile.txt --profile default

      - name: Configure CMake
        run: cmake ${{github.workspace}}/test -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RELEASE

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config RELEASE

      - name: Run
        working-directory: ${{github.workspace}}/build
        run: ctest -C RELEASE
